= Knative connectors

Knative eventing connectors based on https://camel.apache.org/camel-kamelets/[Apache Camel Kamelets].
Each connector project is able to act as a source or sink for the Knative eventing broker.
The projects create container images that get referenced in a Knative KameletSource/KameletSink custom resource.

== Create new connectors

You can use a Maven archetype to generate new connector modules in this project.
The archetype should give you a good start into the new connector project as it generates the basic folder structure and some source files.

You need to build the Maven archetype locally first before using it for the first time:

[source,shell]
----
mvn install -pl :kn-connector-archetype-source
----

The command creates the Maven archetype artifact on your local machine, so you can use it in the Maven `archetype:generate` command:

NOTE: The Maven archetype `kn-connector-archetype-source` creates a new KameletSource connector. You can do the very same for sinks, too.

[source,shell]
----
mvn archetype:generate \
 -DarchetypeGroupId=dev.knative.eventing \
 -DarchetypeArtifactId=kn-connector-archetype-source \
 -DarchetypeVersion=1.0-SNAPSHOT
----

This command starts the archetype generation in interactive mode.
In interactive mode the prompt asks you to provide some more information such as the Kamelet name that you want to use in this kn-connector source.
Also, you may want to customize the Apache Camel component name that is used in the Kamelet (e.g. `aws-s3` as Kamelet name and `aws2-s3` as Apache Camel component name).

After the `archetype:generate` command has finished you will find a new project folder that is ready to be built with Maven.

You can also avoid the interactive mode when specifying all input parameters:

[source,shell]
----
mvn archetype:generate \
 -DarchetypeGroupId=dev.knative.eventing \
 -DarchetypeArtifactId=kn-connector-archetype-source \
 -DarchetypeVersion=1.0-SNAPSHOT \
 -DartifactId=aws-s3-source \
 -Dkamelet-name=aws-s3 \
 -Dcomponent-name=aws2-s3
----

== Build the container image

Each kn-connector project uses Quarkus in combination with Apache Camel, Kamelets and Maven as a build tool.

You can use the following Maven commands to build the container image.

[source,shell]
----
./mvnw package -Dquarkus.container-image.build=true
----

The container image uses the project version and image group defined in the Maven POM.
You can customize the image group with `-Dquarkus.container-image.group=my-group`.

By default, the container image looks like this:

[source,text]
----
quay.io/openshift-knative/kn-connector-{{source-name}}:1.0-SNAPSHOT
----

The project leverages the Quarkus Kubernetes and container image extensions so you can use Quarkus properties and configurations to customize the resulting container image.

See these extensions for details:
* https://quarkus.io/guides/deploying-to-kubernetes
* https://quarkus.io/guides/container-image

== Push the container image

[source,shell]
----
./mvnw package -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
----

Pushes the image to the image registry defined in the Maven POM.
The default registry is https://quay.io/[quay.io].

You can customize the registry with `-Dquarkus.container-image.registry=localhost:5001` (e.g. when connecting to local Kind cluster).

In case you want to connect with a local cluster like Kind or Minikube you may also need to set `-Dquarkus.container-image.insecure=true`.

== Kubernetes manifest

The build produces a Kubernetes manifest in (`target/kubernetes/kubernetes.yml`).
This manifest holds all resources required to run the application on your Kubernetes cluster.

You can customize the Kubernetes resources in `src/main/kubernetes/kubernetes.yml`.
This is being used as a basis and Quarkus will generate the final manifest in `target/kubernetes/kubernetes.yml` during the build.

== Deploy to Kubernetes

You can deploy the application to Kubernetes with:

[source,shell]
----
./mvnw package -Dquarkus.kubernetes.deploy=true
----

This deploys the application to the current Kubernetes cluster that you are connected to (e.g. via `kubectl config set-context --current` and `kubectl config view --minify`).

You may change the target namespace with `-Dquarkus.kubernetes.namespace=my-namespace`.

== Configuration

Each Kamelet defines a set of properties.
The user is able to customize these properties when running a connector deployment.

=== Environment variables

You can customize the properties via environment variables on the deployment:

The environment variables that overwrite properties on the Kamelet source follow a naming convention:

* CAMEL_KAMELET_{{KAMELET_NAME}}_{{PROPERTY_NAME}}={{PROPERTY_VALUE}}

The name represents the name of the Kamelet source as defined in the https://camel.apache.org/camel-kamelets/[Kamelet catalog].

You can set the environment variable on the running deployment:

[source,shell]
----
kubectl set env deployment/kn-connector-{{source-name}} CAMEL_KAMELET_TIMER_SOURCE_MESSAGE="I updated it..."
----

=== ConfigMap and Secret

You may also mount a configmap/secret to overwrite Kamelet properties with values from the configmap/secret resource.

You can reference the values of the configmap in the environment variables like this:

* CAMEL_KAMELET_TIMER_SOURCE_MESSAGE={{configmap:kn-source-config/message}}
* CAMEL_KAMELET_TIMER_SOURCE_PERIOD={{configmap:kn-source-config/period}}

The configmap property values follow this general syntax:

[source,text]
----
configmap:name/key[:defaultValue]
----

The syntax for referencing a secret value in an environment variable is as follows:

[source,text]
----
secret:name/key[:defaultValue]
----

The configmap and secret based configuration requires to add a volume and volume-mount configuration to the connector deployment.
Please refer to the individual source/sink project documentation for more detailed description on how to use configmaps and secrets as a configuration.

== CloudEvent attributes

Each connector produces/consumes events in CloudEvent data format.
The connector source uses a set of default values for the CloudEvent attributes:

* _ce-type_: dev.knative.connector.event.{{source-type}}
* _ce-source_: dev.knative.eventing.{{source-name}}
* _ce-subject_: {{source-name}}

You can customize the CloudEvent attributes with setting environment variables on the deployment.

* KN_CONNECTOR_CE_OVERRIDE_TYPE=value
* KN_CONNECTOR_CE_OVERRIDE_SOURCE=value
* KN_CONNECTOR_CE_OVERRIDE_SUBJECT=value

You can set the CE_OVERRIDE attributes on a running deployment.

[source,shell]
----
kubectl set env deployment/kn-connector-{{source-name}} KN_CONNECTOR_CE_OVERRIDE_TYPE=custom-type
----

You may also use the SinkBinding `K_CE_OVERRIDES` environment variable set on the deployment.

== Dependencies

The required Camel dependencies need to be added to the Maven POM before building and deploying.
You can use one of the Kamelets available in the https://camel.apache.org/camel-kamelets/[Kamelet catalog] as a source or sink in this connector.

Typically, the Kamelet is backed by a Quarkus Camel extension component dependency that needs to be added to the Maven POM.
The Kamelets in use may list additional dependencies that we need to include in the Maven POM.

== Custom Kamelets

Creating a new kn-connector project is very straightforward.
You may copy one of the sample projects and adjust the reference to the Kamelets.

Also, you can use the Camel JBang kubernetes export functionality to generate a Maven project from a given Pipe YAML file.

[source,shell]
----
camel kubernetes export my-pipe.yaml --runtime quarkus --dir target
----

This generates a Maven project that you can use as a starting point for the kn-connector project.

The connector is able to reference all Kamelets that are part of the https://camel.apache.org/camel-kamelets/[default Kamelet catalog].

In case you want to use a custom Kamelet, place the `*.kamelet.yaml` file into `src/main/resources/kamelets`.
The Kamelet will become part of the built container image, you can just reference the Kamelet in the Pipe YAML file as a source or sink.

== More configuration options

For more information about Apache Camel Kamelets and their individual properties see https://camel.apache.org/camel-kamelets/.

For more detailed description of all container image configuration options please refer to the Quarkus Kubernetes extension and the container image guides:

* https://quarkus.io/guides/deploying-to-kubernetes
* https://quarkus.io/guides/container-image
